# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  sensorhub-firmware = pkgs.callPackage (
    { stdenvNoCC, fetchurl }:
    stdenvNoCC.mkDerivation (finalAttrs: {
      pname = "sensorhub-firmware";
      version = "2025.04.14";

      src = fetchurl {
        url = "https://github.com/dantmnf/zenbook-s14-linux/raw/refs/heads/master/firmware/intel/ish/ish_lnlm_ef534c00_fb3b8d86.bin";
        hash = "sha256-AdlQVdGuuy4leUZbR93aOW13t8BIZiyuB5FJpUbky0M=";
      };

      dontUnpack = true;
      dontFixup = true; # binaries must not be stripped or patchelfed

      installPhase = ''
        runHook preInstall

        mkdir -p $out/lib/firmware/intel/ish/
        cp $src $out/lib/firmware/intel/ish/ish_lnlm.bin

        runHook postInstall
      '';
    })
  ) { };
  my-alsa-ucm = pkgs.alsa-ucm-conf.overrideAttrs (oldAttrs: {
    version = "1.2.15.3";
    src = pkgs.fetchurl {
      url = "mirror://alsa/lib/alsa-ucm-conf-1.2.15.3.tar.bz2";
      hash = "sha256-n3noE8CPyGz6Rt11xPzaGkpRtILbJgfh/PqvuS9YijE=";
    };
    # Override the installPhase to avoid problematic substitutions
    installPhase = ''
      mkdir -p $out/share/alsa
      cp -r ucm2 $out/share/alsa/
    '';
    # Disable postInstall to avoid substitutions
    postInstall = "";
  });
  ALSA_CONFIG_UCM = "${my-alsa-ucm}/share/alsa/ucm";
  ALSA_CONFIG_UCM2 = "${my-alsa-ucm}/share/alsa/ucm2";
  env = {
    inherit ALSA_CONFIG_UCM ALSA_CONFIG_UCM2;
  };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.systemd.enable = true; # For hibernation
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl = {
    "vm.swappiness" = 1;
  };
  zramSwap = {
    enable = true;
    memoryPercent = 50;
    memoryMax = 8589934592;
  };

  hardware.enableAllFirmware = true;
  services.hardware.bolt.enable = true;
  services.asusd.enable = true;
  systemd.services.asusd.environment.RUST_LOG =
    "info,asusd=debug,rog_platform=debug,tracing::span=error";

  environment.systemPackages = with pkgs; [
    alsa-topology-conf
    alsa-firmware
    alsa-utils
    my-alsa-ucm
  ];

  environment.variables = env;
  environment.sessionVariables = env;
  systemd.user.services.pipewire.environment = {
    inherit ALSA_CONFIG_UCM ALSA_CONFIG_UCM2;
  };
  systemd.user.services.wireplumber.environment = {
    inherit ALSA_CONFIG_UCM ALSA_CONFIG_UCM2;
  };

  hardware.cpu.intel.npu.enable = true;

  hardware.firmware = [
    sensorhub-firmware
    pkgs.sof-firmware
    pkgs.linux-firmware
    pkgs.alsa-firmware
  ];

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        Experimental = true;
      };
    };
  };

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      intel-vaapi-driver
      libva-vdpau-driver
      libvdpau-va-gl
      vpl-gpu-rt
      intel-compute-runtime
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;
}
