# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  my-alsa-ucm = pkgs.alsa-ucm-conf.overrideAttrs (oldAttrs: {
    version = "1.2.14";
    src = pkgs.fetchurl {
      url = "mirror://alsa/lib/alsa-ucm-conf-1.2.14.tar.bz2";
      hash = "sha256-MumAn1ktkrl4qhAy41KTwzuNDx7Edfk3Aiw+6aMGnCE=";
    };
    # Override the installPhase to avoid problematic substitutions
    installPhase = ''
      mkdir -p $out/share/alsa
      cp -r ucm2 $out/share/alsa/
    '';
    # Disable postInstall to avoid substitutions
    postInstall = "";
  });
  ALSA_CONFIG_UCM = "${my-alsa-ucm}/share/alsa/ucm";
  ALSA_CONFIG_UCM2 = "${my-alsa-ucm}/share/alsa/ucm2";
  env = {
    inherit ALSA_CONFIG_UCM ALSA_CONFIG_UCM2;
  };
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.enableAllFirmware = true;
  services.asusd.enable = true;

  environment.systemPackages = with pkgs; [
    alsa-topology-conf
    alsa-firmware
    alsa-utils
    my-alsa-ucm
  ];

  environment.variables = env;
  environment.sessionVariables = env;
  systemd.user.services.pipewire.environment = {
    inherit ALSA_CONFIG_UCM ALSA_CONFIG_UCM2;
  };
  systemd.user.services.wireplumber.environment = {
    inherit ALSA_CONFIG_UCM ALSA_CONFIG_UCM2;
  };

  # sound
  hardware.firmware = [
    pkgs.sof-firmware # Intel sound DSP firmware
    pkgs.linux-firmware # includes cs35l56-* & friends
    pkgs.alsa-firmware
  ];

  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        Enable = "Source,Sink,Media,Socket";
        Experimental = true;
      };
    };
  };

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vaapiIntel
      vaapiVdpau
      libvdpau-va-gl
      intel-compute-runtime
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;
}
