keys:
  - &xin age1uw059wcwfvd9xuj0hpqzqpeg7qemecspjrsatg37wc7rs2pumfdsgken0c
  - &host-laptop age1ytwfqfeez3dqtazyjltn7mznccwx3ua8djhned7n8mxqhw4p6e5s97skfa
creation_rules:
  - path_regex: machines/calcite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-laptop
  - path_regex: machines/secrets.yaml
    key_groups:
    - age:
      - *xin
  - path_regex: home/xin/secrets.yaml
    key_groups:
    - age:
      - *xin
