keys:
  - &xin age1uw059wcwfvd9xuj0hpqzqpeg7qemecspjrsatg37wc7rs2pumfdsgken0c
  - &host-calcite age1ytwfqfeez3dqtazyjltn7mznccwx3ua8djhned7n8mxqhw4p6e5s97skfa
  - &host-raspite age1nugzw24upk8pz5lyz2z89qk8se4gpcsg3ypcs58nykncr56sevrsm8qpvj
  - &host-la-00 age1fw2sqaa5s9c8ml6ncsexkj8ar4288387ju92ytjys4awf9aw6smqqz94dh
  - &host-massicot age1jle2auermhswqtehww9gqada8car5aczrx43ztzqf9wtcld0sfmqzaecta
  - &host-weilite age17r3fxfmt6hgwe984w4lds9u0cnkf5ttq8hnqt800ayfmx7t8t5gqjddyml
  - &host-hk-00 age1p2dlc8gfgyrvtta6mty2pezjycn244gmvh456qd3wvkfwesp253qnwyta9
  - &host-fra-00 age18u4mqrhqkrpcytxfxfex6aeap04u38emhy6u4wrp5k62sz2vae4qm5jj7s
  - &host-biotite age1v5h946jfke6ae8pcgz52mhj26cacqcpl9dmmrrkf37x55rnq2v3szqctvv
  - &host-thorite age12ng08vjx5jde5ncqutwkd5vm4ygfwy33mzhzwe0lkxzglulgpqusc89r96
creation_rules:
  - path_regex: machines/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-calcite
      - *host-massicot
      - *host-thorite
      - *host-biotite
  - path_regex: machines/calcite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-calcite
  - path_regex: machines/raspite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-raspite
  - path_regex: machines/massicot/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-massicot
  - paht_regex: machines/biotite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-biotite
  - path_regex: machines/thorite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-thorite
  - path_regex: machines/dolomite/secrets/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-la-00
      - *host-hk-00
      - *host-fra-00
  - path_regex: machines/dolomite/secrets/la-00.yaml
    key_groups:
    - age:
      - *xin
      - *host-la-00
  - path_regex: machines/dolomite/secrets/hk-00.yaml
    key_groups:
    - age:
      - *xin
      - *host-hk-00

  - path_regex: machines/dolomite/secrets/fra-00.yaml
    key_groups:
    - age:
      - *xin
      - *host-fra-00
  - path-regex: machines/weilite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-weilite
  - path_regex: home/xin/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-raspite
      - *host-calcite
