keys:
  - &xin age1uw059wcwfvd9xuj0hpqzqpeg7qemecspjrsatg37wc7rs2pumfdsgken0c
  - &host-calcite age1ytwfqfeez3dqtazyjltn7mznccwx3ua8djhned7n8mxqhw4p6e5s97skfa
  - &host-raspite age1nugzw24upk8pz5lyz2z89qk8se4gpcsg3ypcs58nykncr56sevrsm8qpvj
creation_rules:
  - path_regex: machines/calcite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-calcite
  - path_regex: machines/raspite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-raspite
  - path_regex: machines/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-calcite
      - *host-raspite
  - path_regex: home/xin/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-raspite
      - *host-calcite
