keys:
  - &xin age1n359y6qkgzypu0lkcy66pfpneskul35xyhrzz3qumjsmeyp2wsuqq0df49
  - &host-laptop age179ldmg92wqsspgujc70hujfgttw0ljxkh7g86w8rqzywx0f7psysrk0cfn
creation_rules:
  - path_regex: secrets/laptop/[^/]+\.yaml$
    key_groups:
    - age:
      - *xin
      - *host-laptop
  - path_regex: secrets/common/[^/]+\.yaml$
    kay_groups:
    - age:
      - *xin
      - *host-laptop   
