keys:
  - &xin age1uw059wcwfvd9xuj0hpqzqpeg7qemecspjrsatg37wc7rs2pumfdsgken0c
  - &host-calcite age1ytwfqfeez3dqtazyjltn7mznccwx3ua8djhned7n8mxqhw4p6e5s97skfa
  - &host-raspite age1nugzw24upk8pz5lyz2z89qk8se4gpcsg3ypcs58nykncr56sevrsm8qpvj
  - &host-sgp-00 age13s6rwd3wjk2x5wkn69tdczhl3l5d7mfmlv90efsv4q67jne43qss9tcakx
  - &host-tok-00 age1t5nw2jx4dw67jkf72uxcxt72j7lq3xyj35lvl09f8kala90h2g2s2a5yvj
  - &host-massicot age1jle2auermhswqtehww9gqada8car5aczrx43ztzqf9wtcld0sfmqzaecta
creation_rules:
  - path_regex: machines/calcite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-calcite
  - path_regex: machines/raspite/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-raspite
  - path_regex: machines/massicot/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-massicot
  - path_regex: machines/dolomite/secrets/sgp-00.yaml
    key_groups:
    - age:
      - *xin
      - *host-sgp-00
  - path_regex: machines/dolomite/secrets/tok-00.yaml
    key_groups:
    - age:
      - *xin
      - *host-tok-00
  - path_regex: machines/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-calcite
      - *host-raspite
      - *host-sgp-00
      - *host-tok-00
  - path_regex: home/xin/secrets.yaml
    key_groups:
    - age:
      - *xin
      - *host-raspite
      - *host-calcite

