{
  imports = [
    ./attic.nix
    ./caddy.nix
    ./ente-photo.nix
    ./hydra.nix
    ./garage.nix
    ./immich.nix
    ./derper.nix
    ./webdav.nix
    ./nix-builders.nix
    ./ocis.nix
    ./transmission.nix
    ./jellyfin.nix
    ./media-download.nix
    ./proxy.nix
    ./rsshub.nix
  ];
}
